### ISSUE TITLE
Avoid archiving single file output

### ISSUE THREAD

**Issue by joeyvanlierop** [firebelley/godot-export#10]
My project exports a single .exe as I am currently using the "Embed Pck" export option. Ideally, I would like to avoid having to unzip every release. This is a very minor/low priority request.

**Comment by firebelley** [comment]
Support for this has been added in v2.0.0 https://github.com/firebelley/godot-export/releases/tag/v2.0.0 via the `archive_single_release_output` input. Please double-check your input configuration after upgrading as some of the inputs for this action have changed: https://github.com/firebelley/godot-export/tree/v2.0.0#inputs

Please feel free to open more issues/bug reports as you find them!
