### ISSUE TITLE
No loader found for resource error on Exporting binaries

### ISSUE THREAD

**Issue by d0tplus** [firebelley/godot-export#107]
**Godot version:**
v4.0.2 - .NET

**OS/device including version:**
Windows 10

**Issue description:**

Hello! Currently, when I use the example configuration in the readme my build logs gets a lot of the following error: 

`No loader found for resource: [insert-scene-here or cs-file-here]` in the logs. 

![chrome_screenshot_github com](https://user-images.githubusercontent.com/95166858/231966917-152ddbcc-cd18-4a7d-9fd9-fa1b0921c768.png)

The build finishes, but the exported game seems to have all the scripts disconnected or at least not working. I tried making a new project, and it happens there too. When I export from the editor on my computer, my scripts are still working. I attached a minimal reproduction project just encase! Not 100% what is going on my end. Sorry in advance if I made a silly mistake somewhere. 

[Example.zip](https://github.com/firebelley/godot-export/files/11229892/Example.zip)

**Comment by firebelley** [comment]
Hello! Your screenshots indicate that you are using the standard version of Godot:
![image](https://user-images.githubusercontent.com/4622925/232041825-ac597722-19bc-4fd0-a76d-ec5ee9d4ff84.png)

I believe all you need to do is use the download url for the mono version of Godot in your workflow configuration. That should fix the problem!
