### ISSUE TITLE
Building with Mono doesnt generate PCK

### ISSUE THREAD

**Issue by nonunknown** [firebelley/godot-export#115]
when exporting process this error message appears, but the process continue:

```
savepack: begin: Packing steps: 102
  ERROR: Must select at least one file to export.
     at: _save_pack_file (editor/export/editor_export_platform.cpp:190)
  ERROR: Save PCK: Failed to export project files.
     at: add_message (editor/export/editor_export_platform.h:178)
```

this is the linux build, but for windows and mac the same happens
the executable is generated, but the pck doesnt go along in the release

**Comment by firebelley** [comment]
Can you please try with the latest release? This issue is quite old so I'm going to close for now, but please feel free to reply if you still have an issue.
