### ISSUE TITLE
Include support for Blender imports

### ISSUE THREAD

**Issue by Snaiel** [firebelley/godot-export#121]
If the project uses Blender file imports this action will not work as Blender is not installed and is not included in the editor settings.

**Comment by Dabnabbit** [comment]
While I understand that this isn't a super simple task, I'd like to second this capability be implemented. It shouldn't be super difficult to add a third wget to download a copy of Blender, and then modify the editor settings to point to the install the latest Linux Blender 3, it's under ~300Mb I'm fairly certain. Just know it would take some tweaking to get it to download, run, install consistently, and then get the godot install settings to aim at it correctly before attempting to build the project package out, and would definitely add some time to the poor worker/runners, BUT it would be a great feature addition

**Comment by killpond** [comment]
https://github.com/firebelley/godot-export/issues/104#issuecomment-1468120942

**Comment by Snaiel** [comment]
> [#104 (comment)](https://github.com/firebelley/godot-export/issues/104#issuecomment-1468120942)

Wow sorry, I thought I had looked through the closed issues. Don't know how I missed that...
