### ISSUE TITLE
Exporting mac target from linux runner fails silently

### ISSUE THREAD

**Issue by dsaltares** [firebelley/godot-export#125]
Using
- firebelley/godot-export@v5.2.0
- Godot 4.1.2

Workflow file https://github.com/dsaltares/game-off-2023/blob/main/.github/workflows/release.yaml.

I get this error in the action log. The action does exit cleanly and it produces a 22B zip file, which is empty.

```
🖥️ Exporting preset game-off-2023-mac
  /home/runner/.local/share/godot/godot_executable/Godot_v4.1.2-stable_linux.x86_64 /home/runner/work/game-off-2023/game-off-2023/game/project.godot --headless --export-release game-off-2023-mac /home/runner/.local/share/godot/builds/game-off-2023-mac/game-off-2023.dmg
  Godot Engine v4.1.2.stable.official.399c9dc39 - https://godotengine.org/
   
  WARNING: Custom cursor shape not supported by this display server.
       at: cursor_set_custom_image (servers/display_server.cpp:480)
  WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
       at: _editor_init (modules/gltf/register_types.cpp:73)
  ERROR: Cannot export project with preset "game-off-2023-mac" due to configuration errors:
  Warning: Notarization is disabled. The exported project will be blocked by Gatekeeper if it's downloaded from an unknown source.
  Code signing: Xcode command line tools are not installed.
  
     at: _fs_changed (editor/editor_node.cpp:9[87](https://github.com/dsaltares/game-off-2023/actions/runs/6723092056/job/18272395832#step:4:91))
  ERROR: Project export for preset "game-off-2023-mac" failed.
     at: _fs_changed (editor/editor_node.cpp:1003)
```

I don't have any notarization nor code signing set up. However, I can export from my local machine, which is a mac. There is a chance this could be a Godot Engine issue to do with cross-exporting. However, perhaps `godot-export` should actually error out and fail the action.

Thanks for building this great action.

**Comment by coelhucas** [comment]
Same here, I used to use [my own fork](https://github.com/softwoolco/godot-export) of the action for 3.X, never had a problem &mdash; without any notarization/code signing.

You can take a look on the code to figure out if it was some change to the action or in Godot itself to make it break the action and generate this empty artifact. Since this project won't have a MacOS version during playtests, I won't be looking at it myself right now, but may on the future.

**Comment by orcharddweller** [comment]
As per Godot docs, when exporting macOS on Linux without codesign you have to set `Codesign` in export settings to `Built-in (ad-hoc only)`

**Comment by firebelley** [comment]
It seems there is a workaround for this now. Going to close, but feel free to reply if there is still an issue here.
