### ISSUE TITLE
Build hanging on export binaries

### ISSUE THREAD

**Issue by Nitwel** [firebelley/godot-export#128]
These are the last two lines GitHub Actions print out when exporting binaries, then it just get's stuck and does nothing. I have no clue how to even debug this.
```
ERROR: Failed to create an autoload, script 'res://lib/globals/event_system.gd' does not inherit from 'Node'.
     at: _create_autoload (editor/editor_autoload_settings.cpp:423)
ERROR: Condition "!info->node" is true. Continuing.
     at: update_autoload (editor/editor_autoload_settings.cpp:550)
```
Might be related to #127

I've tested it against Godot 4.2 and 4.2.1-rc1, neither did work.

**Comment by moorbren** [comment]
I've had this issue before, have you tried adding `extends Node` to your autoload script? I remember Godot being super whiny about autoload scripts

**Comment by firebelley** [comment]
Is this still an issue? This looks to be a Godot issue and not necessarily an issue with this action. But please feel free to reply if you feel otherwise. Going to close for now.
