### ISSUE TITLE
Control over which presets are built

### ISSUE THREAD

**Issue by maximiliancsuk** [firebelley/godot-export#130]
Hello,

AFAICT, the action will always try to build ALL presets configured in export_presets.cfg. But I have many presets and only want to build some of them through Github actions.
So I'm looking for a way to either whitelist or blacklist specific build presets, to have more control over which presets get built and which get skipped. But I couldn't find a config setting for this. Am I missing something? Or is it possible to add this functionality?

Thanks a lot! :)

**Comment by moorbren** [comment]
@maximiliancsuk See this pull request right here if you want this feature, I've had it ready for a while now: #116

**Comment by maximiliancsuk** [comment]
Super cool, thanks so much for your work! :)

I've turned my attention to other work in the meantime and hence will wait for a bit. Maybe your pull request gets merged soon anyway Fingers crossed! 🤞

**Comment by firebelley** [comment]
This is now released! Thanks!
