### ISSUE TITLE
Run on tag creation

### ISSUE THREAD

**Issue by ankhers** [firebelley/godot-export#15]
Is it currently possible to run this on tag creation and have it upload to that tag instead of creating a tag of its own?

**Comment by firebelley** [comment]
Hi there! That is currently not supported, but sounds like something worth looking into supporting! Please feel free to provide suggestions on what the action configuration might look like to support that.

**Comment by dardanbujupaj** [comment]
@ankhers, @firebelley 
Hi. Just needed this exact thing.
While tinkering around, I found a solution.
I created a pull request #22 adding an example to the README-File.

**Comment by firebelley** [comment]
Thanks @dardanbujupaj, good find!
