### ISSUE TITLE
How to deploy to gh-pages branch?

### ISSUE THREAD

**Issue by tylerecouture** [firebelley/godot-export#16]
Is there a way to use this to deploy the code to a gh-pages branch for use in github.io site?

I'm trying to combine what you have with this:
https://github.com/JamesIves/github-pages-deploy-action

But I don't know how to get the exported source for that action.

I tried setting:
 `create_release: false`  but it didn't create an exports folder anywhere on my project to get the exported game.

**Comment by firebelley** [comment]
Setting `create_release` to `false` will add your zipped binaries to an `exports` directory at the level of your `project.godot` file. Please note that this action does not _commit_ those changes, you will have to take an action to commit those files to your repo yourself. If you do not commit those changes they will be lost and there will be no persisted `exports` directory.

Maybe using another action to do the commit after `godot-export` runs would do the trick? This seems to be a good one https://github.com/stefanzweifel/git-auto-commit-action

**Comment by tylerecouture** [comment]
Thanks for the tip!  Is there a way to get the non-zipped files put in that directory instead of zipped?

**Comment by firebelley** [comment]
You're welcome! There is not currently a way to do that, however I can support that along with #10 

By all means, feel free to contribute that feature! Otherwise feature requests are tackled as I can find time to get to them, so it may be a bit of waiting before that is supported

**Comment by firebelley** [comment]
Addressed in #17
