### ISSUE TITLE
Ability to chose export location

### ISSUE THREAD

**Issue by tylerecouture** [firebelley/godot-export#18]
Currently, the export directory is created within `relative_project_path` but it would be nice to be able to put it somewhere else, including the repo's root directory (if different from the godot project's root) and/or a different name for the export directory.

For example someone might want to use github pages' ability to auto-read the `/docs` directory of a repository

**Comment by firebelley** [comment]
Support for this has been added in v2.0.0 https://github.com/firebelley/godot-export/releases/tag/v2.0.0 via the `relative_export_path` input. Please double-check your input configuration after upgrading as some of the inputs for this action have changed: https://github.com/firebelley/godot-export/tree/v2.0.0#inputs

Please feel free to open more issues/bug reports as you find them!
