### ISSUE TITLE
Possible Platforms

### ISSUE THREAD

**Issue by AwesomeKalin** [firebelley/godot-export#33]
What platforms are possible? Is it just Windows, Mac and Linux?

**Comment by firebelley** [comment]
This action can export to any platform that Godot can export to. The caveat is for things like Android and iOS, you need to make sure your workflow environment has the necessary prerequisites.

But Windows, Mac, Linux, and HTML5 should all work out-of-the-box with no additional workflow configuration needed.

**Comment by AwesomeKalin** [comment]
Thanks
