### ISSUE TITLE
Error: The process '/home/runner/.local/share/godot/godot_executable/godot' failed with exit code 1 when building for linux (64-bit)

### ISSUE THREAD

**Issue by AwesomeKalin** [firebelley/godot-export#34]
I'm having an issue where, when building for Linux 64-bit, it just crashes. I have 1 addon, Zylann's Terrain addon. Here is the run if you want to see if it's on my side:
https://github.com/Awesome-Arcade/Mazerator/runs/1271633001?check_suite_focus=true
You can also use this to check my code or Workflow file. For now, I'll try and stop linux from building

**Comment by firebelley** [comment]
This appears to be an issue with the Godot build process itself, and not with this action. You have the following error in your output:

```
ERROR: copy: Failed to open res://addons/zylann.hterrain/native/bin/linux/hterrain_native.so
     At: core/os/dir_access.cpp:298.
  ERROR: _fs_changed: Project export failed for preset 'linux64', the export template appears to be missing.
     At: editor/editor_node.cpp:638.
```

I'm not sure how to resolve that, but this action is not the cause of the error.

**Comment by AwesomeKalin** [comment]
It could be fixed by upgrading to the latest version of Godot OR changing the version of the addon to the master branch. I'll try both methods and go forwards from there. Thanks!
