### ISSUE TITLE
add-path warning - will be disabled soon

### ISSUE THREAD

**Issue by d4rkd0s** [firebelley/godot-export#35]
When using this firebelley/godot-export, on v2.4.0

```
- name: export game
  uses: firebelley/godot-export@v2.4.0
```

My pipeline started giving me this error,

![image](https://user-images.githubusercontent.com/2348814/96937160-25ad7100-148d-11eb-8b7b-689823d453a3.png)

It looks like add-path command is being removed. See this blogpost from GitHub:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

> "We are monitoring telemetry for the usage of these commands and plan to fully disable them in the future."

I believe the following line of code would need to be changed,
https://github.com/firebelley/godot-export/blob/5c86ca18e7a3785be0c0a8c731aa1d97b2a79595/src/godot.ts#L106

**Comment by firebelley** [comment]
Thank you for bringing this to my attention, it looks like updating `@actions/core` should fix it. I'll make time this weekend to address it, alternatively if you'd like to upgrade the package please feel free to do so!

**Comment by d4rkd0s** [comment]
@firebelley looks like you already bumped to `"@actions/core": "^1.2.6",`
here: https://github.com/firebelley/godot-export/commit/5c86ca18e7a3785be0c0a8c731aa1d97b2a79595

Just taking notes

**Comment by firebelley** [comment]
Just released v2.5.0 which should resolve the warning https://github.com/firebelley/godot-export/releases/tag/v2.5.0

**Comment by d4rkd0s** [comment]
![image](https://user-images.githubusercontent.com/2348814/97498885-f4c0b680-193a-11eb-9491-61c2d35f7c80.png)
Tested bumping from v2.4.0 to v2.5.0 and the annotation is gone.

The fix worked, thank you @firebelley 👏
