### ISSUE TITLE
Include export directory itself in release archives

### ISSUE THREAD

**Issue by outfrost** [firebelley/godot-export#38]
Currently, when uploading release assets, `godot-export` archives the contents of the build directory (e.g. the executable and PCK for Linux exports) directly in the zip.

Several of our players have expressed that it would be more convenient if the zip contained a directory, which would then in turn contain the executable and data, as it eliminates the possibility of accidentally mixing the game's files with unrelated ones.

When using `use_preset_export_path`, could the action also have a setting to archive the export directory itself, instead of just the contents?

For example:
* My export preset is called `Game-Linux-X11-amd64`
* Currently, the zip in the generated release looks like this:
    ```
    - Game-Linux-X11-amd64.zip
    |-- Game.pck
    |-- Game.x86_64
    ```
* I would like it to look like:
    ```
    - Game-Linux-X11-amd64.zip
    |-- Game-Linux-X11-amd64
      |-- Game.pck
      |-- Game.x86_64
    ```

**Comment by firebelley** [comment]
Thanks for suggesting this! I'm currently experimenting with streamlining this action, so that it is more configurable and less bloated. I'll keep this use-case in mind when working on it. If that doesn't end up working out, I will add this functionality as an additional optional input.

**Comment by firebelley** [comment]
Apologies for the (very) long delay. I finally got around to the overhaul I wanted to do, so I will queue this up for the next release 👍

**Comment by firebelley** [comment]
This has been added with v4.1.0

**Comment by outfrost** [comment]
Thanks! <3
