### ISSUE TITLE
Please add Android Custom Build

### ISSUE THREAD

**Issue by gustavottc** [firebelley/godot-export#39]
Will be more easier to export and test games that uses plugins:

https://docs.godotengine.org/en/stable/getting_started/workflow/export/android_custom_build.html

**Comment by firebelley** [comment]
As far as I can tell, you should be able to just add this to your repo and commit it. I don't think there's anything that this action needs to do to support that.

**Comment by gustavottc** [comment]
I don't think so, because what Godot does when it installs is to extract the .zip called "```android_source.zip```" that is inside the "```export_templates.tpz```", this folder weighs 80MB, if you commit it to the repository, it will weigh a lot, besides that when the plugin is compiled on Godot, that folder weighs more than 1GB, if it is sent into the repository it will not be a good thing.

But I thought of a solution for this: Before calling your action, I can download "```export_templates.tpz```", extract the "android_source.zip" folder into the project and send the plugins into the "```android/plugins```" folder, this should work, the bad thing is that it will take longer because it will download 2x the same file "```export_templates.tpz```"

Another question: Is it possible to ask Action to export only to one platform? 
Example: ```export_presets.cfg``` has presets for iOS and Android and I want to export only to Android

Thank you so much.

**Comment by firebelley** [comment]
I see, yeah doing it as an extra step sounds like the way to do it.

There's no official way to export only 1 platform, however if you leave the export path empty for an export preset this action will skip it.

I will definitely consider adding a formal way of selecting explicit presets to export!
