### ISSUE TITLE
[ERROR] Export for Android not working (ADB and Debug keystore not configured)

### ISSUE THREAD

**Issue by gustavottc** [firebelley/godot-export#40]
ERROR: _fs_changed: Cannot export project with preset 'Android' due to configuration errors:
  ADB executable not configured in the Editor Settings.
  Debug keystore not configured in the Editor Settings nor in the preset.
  
     At: editor/editor_node.cpp:730.
  ERROR: _fs_changed: Project export failed with error code 3 for preset 'Android'.
     At: editor/editor_node.cpp:753.
  EditorSettings: Save OK!
  Error: The process '/home/runner/.local/share/godot/godot_executable/godot' failed with exit code 1

workflow: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/runs/1392365046?check_suite_focus=true

**Comment by firebelley** [comment]
I'm not too familiar with Android export, but I think you might need additional editor settings? This file https://github.com/firebelley/godot-export/blob/master/dist/editor_settings-3.tres gets copied to the appropriate directory before export happens.

So there are two approaches here:
- You could update that file in your own fork of this repo, and use your forked action with the updated editor settings in your workflow. If you do that please open a PR against this repo with the changes 😄 
- I have a to-do on my list to allow users of this action to copy their own editor settings file before this action runs. But I can't guarantee that I would get that done soon - I have to find time to do it

Let me know if that doesn't make sense, I am happy to explain further!

**Comment by gustavottc** [comment]
I will try to see this soon, I'm currently working on a mono compiled version, thank you

**Comment by gustavottc** [comment]
Please approve #41 , worked: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/actions/runs/373552938, failed due i am trying to test on XCode but it's not complete, thank you.

And i guess theres some way to improve this, because iam generating by myself the debug.keystore and moving the adb to /usr/bin, maybe this is not the best way to do that

**Comment by firebelley** [comment]
Hi, thanks for the PR. Please look at my comment here https://github.com/firebelley/godot-export/pull/41#issuecomment-731848435

I think it's probably better to allow people to copy a custom `editor_settings-3.tres` file before running the action, and to not overwrite it if it exists when the action runs. It'll be an extra step in your workflow but I think this solution is going to be the best going forward.

Please let me know if you have further issues!
