### ISSUE TITLE
what is the format for the relative path when its not in the root dir?

### ISSUE THREAD

**Issue by PoisnFang** [firebelley/godot-export#47]
My repo has 4 godot projects, should look like this "/root/game/godot.project" I cant get the workflow to find it though...

**Comment by PoisnFang** [comment]
ok I figured it out,
its "./game"
ALSO I didnt realize that the [default .gitignore](https://github.com/github/gitignore/blob/master/Godot.gitignore) has `export_presets.cfg`

**Comment by firebelley** [comment]
Glad you figured it out 👍
