### ISSUE TITLE
Android export

### ISSUE THREAD

**Issue by ricardoalcantara** [firebelley/godot-export#49]
Why adb path is hardcoded in the editor_settings-3.tres if adb is not provided?

I tried to use this action https://github.com/android-actions/setup-android that setup android sdk for me.

And I had to fork this repository to change its path
https://github.com/ricardoalcantara/godot-export/blob/master/dist/editor_settings-3.tres

I noticed that here 
https://github.com/firebelley/godot-export/blob/master/src/godot.ts#L258

you write two properites in that editor_settings, 

Couldn't any editor_settings be input in this action?

Thanks!

**Comment by firebelley** [comment]
The way that this action works is that it won't make changes to
editor_settings if it exists already. So what you can do in your workflow
is copy your custom editor_settings to the correct directory before the
action runs. See the bottom of the readme for more details. Let me know if
you have any questions!

**Comment by ricardoalcantara** [comment]
I apologise for my lack of attention, I read the whole README.md but maybe I was too anxious plus this is my first pipeline, I totally misread that information about how to overide the editor settings.

Now everything's working.

Thanks for all your effort.
