### ISSUE TITLE
Android export: more docs and sensible defaults

### ISSUE THREAD

**Issue by pierpo** [firebelley/godot-export#50]
Hi!

Thank you for the amazing github action. This is super helpful, I love it.

I had a hard time in getting the Android export to work, though. The steps I went through:

- Does the action include the Android installation?
  - answer: no
- How do I easily install Android?
  - answer: the following action works perfectly https://github.com/android-actions/setup-android
- Android is set-up, but I still get errors. The SDK path is not valid, says Godot.
  - answer: it turns out that the default SDK config looked like it was compatible with `setup-android`, but it wasn't really. Here's the diff:
 
```diff
  [gd_resource type="EditorSettings" format=2]

  [resource]
+ export/android/android_sdk_path = "/usr/local/lib/android/sdk"
- export/android/adb = "/usr/bin/adb"
- export/android/jarsigner = "/usr/bin/jarsigner"
- export/android/custom_build_sdk_path = "/usr/local/lib/android/sdk"
  mono/builds/build_tool = 0
```

First, no `adb` nor `jarsigner` are installed in `/usr/bin`. Then, the `custom_build_sdk_path` didn't work for me. Maybe it's linked to the fact that I do not use a custom build template (in that case, it's super weird of Godot to differenciate a SDK for a custom build or default build, but well).

Two questions:
- Do you think we should give a guide through these steps?
- Should we change the default values?

If you agree with those, I could handle it if you want.

Thanks :hugs:

**Comment by firebelley** [comment]
I'm super happy to hear that you like this action! 

It seems that Android is a unique case for every user, the default values were a response to an original issue where the editor-settings lacked Android paths.

I think the most sensible thing to do going forward is to **remove all of the default Android paths**, and document how users of this action can implement Android support now that users can supply their own `editor_settings-3.tres`.

If you can handle those changes, it would be greatly appreciated!

**Comment by firebelley** [comment]
These issues were addressed in the latest version: https://github.com/firebelley/godot-export/releases/tag/v2.7.0

**Comment by pierpo** [comment]
Oh, fantastic! Sorry that I didn't answer, I was planning to do it in the coming days/weeks :smile: 
Thanks!
