### ISSUE TITLE
ERROR: initialize: X11 Display is not available

### ISSUE THREAD

**Issue by telmotrooper** [firebelley/godot-export#59]
I've set up [a GitHub action](https://github.com/telmotrooper/squash-the-creeps/blob/main/.github/workflows/main.yml) using __godot-export__ in my repository, the problem is when I get to the "export game" step I get the following error:

```
Using project file at /home/runner/work/squash-the-creeps/squash-the-creeps/my-3d-squash-the-creeps/project.godot
/home/runner/.local/share/godot/godot_executable/godot /home/runner/work/squash-the-creeps/squash-the-creeps/my-3d-squash-the-creeps/project.godot --export Linux/X11 /home/runner/.local/share/godot/builds/LinuxX11/squash_01-06-2021_01-06.x86_64 --verbose
ERROR: initialize: X11 Display is not available
   At: platform/x11/os_x11.cpp:129.
Godot Engine v3.3.2.stable.official - https://godotengine.org
Error: The process '/home/runner/.local/share/godot/godot_executable/godot' failed with exit code 255
```
I don't see anything obviously wrong in my action (which was based in the [example configuration](https://github.com/firebelley/godot-export#example-configuration)) and the export settings used work locally.

Can someone lend me a hand? Thank you a lot!

**Comment by firebelley** [comment]
Hi, can you please make sure you are using the headless version of Godot in
your action?

**Comment by telmotrooper** [comment]
@firebelley This was indeed the issue. Replacing the value of `godot_executable_download_url` from:

`https://downloads.tuxfamily.org/godotengine/3.3.2/Godot_v3.3.2-stable_x11.64.zip`

to:

`https://downloads.tuxfamily.org/godotengine/3.3.2/Godot_v3.3.2-stable_linux_headless.64.zip`

solved my issue.

Thank you for the help and for implementing this very useful action. :slightly_smiling_face:

**Comment by firebelley** [comment]
Great! You're welcome, happy to help 🙂
