### ISSUE TITLE
Release customization

### ISSUE THREAD

**Issue by knightofiam** [firebelley/godot-export#61]
This might seem counterproductive, but I'd like to be able to create releases with only the source code and not the executables, since I'm already uploading to itch.io and I don't want to have them in two places. I * could * just write my own release code and set `create_release: false`, but since I'm using your plugin...

**Comment by firebelley** [comment]
Thanks for the suggestion! However, I think this would be better achieved by using an already available release action. Please see the "maintained actions" section here: https://github.com/actions/create-release (I would have recommended actions/create-release but GitHub is no longer maintaining it)

Please feel free to submit more suggestions as you have them!

**Comment by knightofiam** [comment]
For posterity, I'm using mknejp/delete-release-assets to achieve this.
