### ISSUE TITLE
Template name error when using RC/Beta versions

### ISSUE THREAD

**Issue by IsjaslawEisenstadt** [firebelley/godot-export#64]
Godot versions like these don't work with this action:
```
godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4/beta3/mono/Godot_v3.4-beta3_mono_linux_headless_64.zip
godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4/beta3/mono/Godot_v3.4-beta3_mono_linux_headless_64.zip
```

The problem is that during the template download, the getGodotVersion inside godot.ts will return a string like: 3.4.beta3.mono.official.2b78308f9

The .official will be filtered out but the .2b78308f9 won't. But godot expects a path like 3.4.beta3.mono by default, that's why it's crashing.

**Comment by firebelley** [comment]
Thanks for the report! If you feel up to it, please submit a PR with a fix. Otherwise I will get to this issue as soon as I have availability 👍
