### ISSUE TITLE
editor_settings-3.tres does not include keystore

### ISSUE THREAD

**Issue by bend-n** [firebelley/godot-export#73]
Why doesnt it automatically generate the keystore and stuff?

**Comment by firebelley** [comment]
The keystore is highly sensitive and needs to be configured on a per-repository basis. You should keep it secret and use something besides the default keystore when working on a commercial product. Please correct me if I am wrong, but that is my understanding.

**Comment by bend-n** [comment]
Not the debug keystore.

**Comment by firebelley** [comment]
You can generate a keystore with the command line in a prior step in your workflow, there is no reason this action needs to do that step.
