### ISSUE TITLE
How to make it create artifact instead of release

### ISSUE THREAD

**Issue by BlockOG** [firebelley/godot-export#74]
I want to just create an artifact for the workflow instead of a release, I can do that manually, I don't want it to release on every commit I do

**Comment by knightofiam** [comment]
This is stated clearly in the README, `create_release` is set to `true` by default, so simply set it to `false`.

**Comment by firebelley** [comment]
@BlockOG this action is being reworked https://github.com/firebelley/godot-export/pull/78

Now this action will only create artifacts and you can use a different create release action or simply upload the artifacts to GitHub. If you have any feedback regarding that PR, I'd love to hear it!
