### ISSUE TITLE
Make godot verbose build optional

### ISSUE THREAD

**Issue by manuel3108** [firebelley/godot-export#75]
See https://github.com/firebelley/godot-export/blob/1e28506c4afa5c7c33c7da60f87b71ccacf4a405/src/godot.ts#L165

This is really spamming the logs with not so interesting stuff. But it might help with debugging in some cases. That's why i propose to make it optional

**Comment by firebelley** [comment]
This is handled in https://github.com/firebelley/godot-export/pull/78. Please let me know what you think if you have comments!

**Comment by manuel3108** [comment]
Thanks! I have added my "short" comment directly on the pr.

**Comment by firebelley** [comment]
This has been addressed in #78 

Thanks so much!
