### ISSUE TITLE
Use GitHub API to generate release notes

### ISSUE THREAD

**Issue by manuel3108** [firebelley/godot-export#76]
Docs: https://docs.github.com/en/rest/releases/releases#create-a-release

Overall, we would propably only need to add one flag to here: https://github.com/firebelley/godot-export/blob/1e28506c4afa5c7c33c7da60f87b71ccacf4a405/src/release.ts#L32
And remove the current code for creating release notes

**Comment by knightofiam** [comment]
Great idea. GitHub's release notes API seems to only list PR's, which is OK for my project as I'm using a PR-based workflow. But I know many are not. It would be great to be able to include ALL commits, and I could have missed something here, but reading over the API docs I haven't seen a way to do this.

**Comment by firebelley** [comment]
@manuel3108 Thank you for the suggestion!

This action is becoming bloated, so I have reworked it significantly here https://github.com/firebelley/godot-export/pull/78

In that PR, the docs show the use of a different action for release creation. It would be great if you could take a look and let me know if this new approach is going to suit your needs! I think that by re-focusing this action on _only_ handling exports then workflow configurations can be far more flexible.

**Comment by manuel3108** [comment]
Great, i completely agree. But we should provide some infrastructure to easily create the releases afterwards.

See my comment on the pr directly.

Closing this, as this is now out of scope for this action.
