### ISSUE TITLE
Make GitHub Release Executables Optional

### ISSUE THREAD

**Issue by knightofiam** [firebelley/godot-export#77]
It would be useful to be able to specify via a boolean flag to not include the zipped executables in the GitHub release, when `create_release` is true. Furthermore, the `archive_*` settings are a bit confusing because they don't actually have anything to do with this feature request, but they ***appear*** to.

The use case for this feature is not wanting my Godot game downloadable from GitHub, as it's being published through Itch.io, and I would like all downloads to go through said channel only. I attempted a workaround of using a GitHub Action that claimed it would delete the assets from a GitHub release, but I tried everything and it would find the version tag correctly, but couldn't find any uploaded assets associated with it. Although I specified the job to run ***after*** your release process, I think it may be a race condition where the assets are still being uploaded when the deletion job runs. I haven't found a way to trigger a deletion job upon completion of release asset uploads, at least not through `godot-export`.

My current workaround is to manually go in and delete the assets via GitHub's web API, which is of course not ideal as I'm building an automated CI/CD pipeline.

The other consideration for implementation of this feature is being able to specify wildcard patterns to match which assets to upload. I would like to keep the zipped source code assets attached to the GitHub release, and be able to specify, e.g., don't upload `mygame-*.zip`, where `*` would represent for example, `mac` / `win` / `linux`, in this case.

**Comment by knightofiam** [comment]
@firebelley I apologize, I forgot about #61. Are you willing to reconsider this feature? 😄

**Comment by firebelley** [comment]
@knightofiam I have decided to rework this action to remove a lot of the bloat. This action will soon only be responsible for doing the exports, and then using other actions to create releases. I think that you'll find this will be much more flexible.

I would appreciate if you'd take some time to look at https://github.com/firebelley/godot-export/pull/78 and let me know what you think! The docs on that branch have been updated to show what the new "Create Release" functionality can look like using a different action. Please feel free to add any comments you may have over on that PR

**Comment by firebelley** [comment]
I believe this has been addressed indirectly with v4.0.0. This action no longer does releases for you. Instead, you can choose a release action to your liking. Feel free to reopen if you feel this is still an issue!
