### ISSUE TITLE
Executable not archived

### ISSUE THREAD

**Issue by firegate666** [firebelley/godot-export#89]
I was following your example for exporting builds, created the export in Godot etc ... but whenever I ran the runner, it only added the ZIPPED project to the release (source code) and not the created win.exe (although the output showed it was created)

I needed to add

    use_preset_export_path: true

to the export step and added an additional archive at the end

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: builds
        path: |
          builds

to get it to work. Now the exe is at least archived. But not added to release.

Then I realized (whiloe looking at the logs) that the variable that is used to point to the release output is not resolving to anything meaningful. You might want to check this

I changed it to the builds folder that you also used in the example and referenced the runner work dir, and then it works

    - name: create release
      uses: softprops/action-gh-release@v0.1.14
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: true
        tag_name: ${{ steps.tag_version.outputs.TAG_VERSION }}
        files: ${{ github.workspace }}/builds/win/win.zip

Ref: https://github.com/firegate666/godot_tutorial_2d_dodge_the_creeps/actions

**Comment by firebelley** [comment]
Hello! Unfortunately the `archive_directory` and `build_directory` outputs do not take into account the preset export path. Note the docs say the following:

The directory containing archived exports. This directory will be empty if archive_output is not set. **Note that the inputs relative_export_path and use_preset_export_path do not change this output value.**

Does this describe why you were experiencing this issue? Or is there something else wrong here?

**Comment by firebelley** [comment]
Please feel free to reopen if the above comment does not address your issue!
