### ISSUE TITLE
Mac build only exporting Debug

### ISSUE THREAD

**Issue by davidjreese** [firebelley/godot-export#90]
The plugin isn't properly building a RELEASE build for Mac. 

My configuration export specified 2 targets.
- macOS
- windows

I have tried specifying the flag _export_debug:false_ (as well as not specifying it). It doesn't seem to matter. My application still has **App Title (Debug)** in the titlebar. For the Windows build, it doesn't seem to be a problem (at least there is no **(Debug)** in the title bar when running that version.

Here is a screenshot of my current config:
<img width="914" alt="Screen Shot 2022-11-01 at 7 41 35 AM" src="https://user-images.githubusercontent.com/669018/199234806-30c85ef1-6fd5-4339-b56e-829f645b53cf.png">

**Comment by firebelley** [comment]
Hello! If you export from a computer like normal from Godot 3.5.1 does the issue still occur? I will take a look at the code but I can't think of how this would be an issue atm.

**Comment by davidjreese** [comment]
Hello, I was just coming to update this. I have some more data. Don't want to have you chase down a false positive so I will do a bit more experimenting after this comment.

1. Building from Godot export dialog => worked fine (release build was there).
2. I reordered the applications, now have Windows building first => this appears to have maybe made a difference!

I distribute on Steam and so I am going to change it back to how it was and delete my steam folder. Given I do development locally to, I want to make sure I wasn't seeing something related to Steam just not properly updating if I overrode the local application file during a debug session.

**Comment by davidjreese** [comment]
I confirmed this is a user error on my part. Steam was not overwriting my local debug application in every scenario so it was still using a locally copied .app package (or at least parts of it since its archive folder under the hood). I will slow it out.

**Comment by firebelley** [comment]
Ok great, glad you figured it out! 👍
