### ISSUE TITLE
Incorrect configuration file for Godot 4 Android support

### ISSUE THREAD

**Issue by santyarellano** [firebelley/godot-export#92]
Hi!
First time submitting an issue here, so please forgive me if I'm missing something.

I'm trying to build for Android using Godot 4 and I noticed that using `use_godot_4` doesn't quite do the trick in this case, as the configuration file should have the sdk location, which is in the `editor_settings-3.tres`, yet when using Godot 4 it's using `editor_settings-4.tres`. I believe it could be an easy fix in the `🔍 Adding Editor Settings` step, but my knowledge only goes so far. 

![image](https://user-images.githubusercontent.com/18352059/202244293-b383472d-1608-4aeb-ae9e-1abe349cb016.png)

Here's my main.yml in case it helps:

      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Export Game
        uses: firebelley/godot-export@v4.2.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/beta1/Godot_v4.0-beta1_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/beta1/Godot_v4.0-beta1_export_templates.tpz
          relative_project_path: ./
          use_preset_export_path: true
          use_godot_4: true

**Comment by firebelley** [comment]
Hello, thanks for reporting this issue! As a workaround in the meantime, you can create your own editor settings file:
https://github.com/firebelley/godot-export#custom-editor-settings
