### ISSUE TITLE
Blender Import Support

### ISSUE THREAD

**Issue by acegiak** [firebelley/godot-export#98]
Currently projects that use automatic blender import get this error during the import stage:
```
   WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
       at: _editor_init (modules/gltf/register_types.cpp:61)
```

Which then means that the import stage doesn't work so there's no .godot folder when building

**Comment by firebelley** [comment]
I think you will also need to install blender in your workflow before running this action. 

Then, I believe you can fix this by supplying your own editor-settings file with the blender path as shown here: https://github.com/firebelley/godot-export#supplying-a-custom-editor-settings-file

Will that solve your issue?

**Comment by firebelley** [comment]
Please feel free to reopen if the above suggestions don't work!
